language: csharp
mono: none
solution: app/webapiApp.sln
# TODO: Config test project
dotnet: 2.1.802
script: 
  - cd app
  - dotnet restore
  - dotnet test
deploy:
  provider: cloudfoundry
  username: davidflores0584@gmail.com
  password: D@vid0584
  api: https://api.run.pivotal.io
  organization: davidflores0584-org
  space: development
  manifest: manifest-dev.yml
